# Generated by Django 5.1.6 on 2025-03-02 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=254, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefono')),
                ('direccion', models.TextField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TituloCertificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título/Certificación')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institución')),
                ('fecha_obtencion', models.DateField(verbose_name='Fecha de Obtención')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos_certificaciones', to='perfiles.perfildocente')),
            ],
        ),
    ]
