# Generated by Django 5.1.6 on 2025-03-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanage',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usermanage',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='HistoricalUserManage',
        ),
        migrations.DeleteModel(
            name='UserManage',
        ),
    ]
