# Generated by Django 5.1.6 on 2025-03-02 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAlertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_alerta', models.CharField(max_length=255, verbose_name='Mensaje de Alerta')),
                ('dias_anticipacion', models.PositiveIntegerField(default=30, verbose_name='Días de Anticipación')),
                ('activa', models.BooleanField(default=True, verbose_name='Alerta Activa')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_docentes', to='perfiles.perfildocente')),
            ],
        ),
    ]
