# Generated by Django 5.1.6 on 2025-03-02 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(choices=[('TP', 'Tiempo Parcial'), ('ABC', 'Cuadros no docente (ABC)'), ('PC', 'Perfil de Competencia')], max_length=3, verbose_name='Tipo de Contrato')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_fin', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('documento', models.FileField(upload_to='contratos/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='perfiles.perfildocente')),
            ],
        ),
    ]
