# Generated by Django 5.1.6 on 2025-03-02 10:40

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalContrato',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo_contrato', models.CharField(choices=[('TP', 'Tiempo Parcial'), ('ABC', 'Cuadros no docente (ABC)'), ('PC', 'Perfil de Competencia')], max_length=3, verbose_name='Tipo de Contrato')),
                ('fecha_inicio', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('fecha_fin', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Actualización')),
                ('documento', models.TextField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical contrato',
                'verbose_name_plural': 'historical contratos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
